cameras:
  - name: left_cam_main
    device: /dev/cam_left
    mode: direct-copy-h265
    width: 1920
    height: 1080
    fps: 60
    output_files: [cam_left.mkv]

  - name: right_cam_main
    device: /dev/cam_right
    mode: direct-copy-h265
    width: 1920
    height: 1080
    fps: 60
    output_files: [cam_right.mkv]

  - name: chest_cam_main
    device: /dev/cam_chest
    mode: direct-copy-h265
    width: 1920
    height: 1080
    fps: 60
    output_files: [cam_chest.mkv]

  - name: left_tcam_l
    device: /dev/tcam_left_l
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [tcam_left_l.mkv]
    input_thread_queue_size: 64

  - name: left_tcam_r
    device: /dev/tcam_left_r
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [tcam_left_r.mkv]
    input_thread_queue_size: 64

  - name: right_tcam_l
    device: /dev/tcam_right_l
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [tcam_right_l.mkv]
    input_thread_queue_size: 64

  - name: right_tcam_r
    device: /dev/tcam_right_r
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [tcam_right_r.mkv]
    input_thread_queue_size: 64
