#ifndef _FAYS_VIK_VERSION_H_
#define _FAYS_VIK_VERSION_H_

#define FAYS_VIK_VERSION_MAJOR 2
#define FAYS_VIK_VERSION_MINOR 7
#define FAYS_VIK_VERSION_PATCH 0

#define FAYS_TO_STRING_HELPER(x) #x
#define FAYS_TO_STRING(x) FAYS_TO_STRING_HELPER(x)
#define FAYS_VIK_VERSION_STRING                 \
  FAYS_TO_STRING(FAYS_VIK_VERSION_MAJOR) "."    \
  FAYS_TO_STRING(FAYS_VIK_VERSION_MINOR) "."    \
  FAYS_TO_STRING(FAYS_VIK_VERSION_PATCH)
#endif /* _FAYS_VIK_VERSION_H_ */