cameras:
  - name: left_cam_main
    device: /dev/left_cam_main
    mode: direct-copy-h265
    uvc_roll_absolute: 4
    width: 1920
    height: 1080
    fps: 60
    output_files: [left_cam_main.mkv]

  - name: right_cam_main
    device: /dev/right_cam_main
    mode: direct-copy-h265
    uvc_roll_absolute: 4
    width: 1920
    height: 1080
    fps: 60
    output_files: [right_cam_main.mkv]

  - name: left_stereo
    device: /dev/left_stereo
    mode: stereo-hybrid-decode-encode
    width: 1280
    height: 400
    fps: 60
    output_fps: 30
    output_files: [left_stereo.mkv]
    input_thread_queue_size: 128
    qp_init: 30
    qp_max: 38
    qp_min: 24
    qp_max_i: 38
    qp_min_i: 20

  - name: right_stereo
    device: /dev/right_stereo
    mode: stereo-hybrid-decode-encode
    width: 1280
    height: 400
    fps: 60
    output_fps: 30
    output_files: [right_stereo.mkv]
    input_thread_queue_size: 128
    qp_init: 30
    qp_max: 38
    qp_min: 24
    qp_max_i: 38
    qp_min_i: 20

  - name: left_tcam_l
    device: /dev/left_tcam_l
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [left_tcam_l.mkv]
    input_thread_queue_size: 64

  - name: left_tcam_r
    device: /dev/left_tcam_r
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [left_tcam_r.mkv]
    input_thread_queue_size: 64

  - name: right_tcam_l
    device: /dev/right_tcam_l
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [right_tcam_l.mkv]
    input_thread_queue_size: 64

  - name: right_tcam_r
    device: /dev/right_tcam_r
    mode: hybrid-decode-encode
    width: 640
    height: 480
    fps: 120
    output_files: [right_tcam_r.mkv]
    input_thread_queue_size: 64
