%YAML:1.0
# Rgb device number
rgb_dev_port: NULL
# auto white balance [true/false]
awb: false
# White balance coefficients
rgb_white_balance_r: 1.3 #1
rgb_white_balance_g: 0.8 #0.7
rgb_white_balance_b: 2.1  #1.66
# RGB image rotation angle, currently only 0/180 degree rotation is supported.
rgb_rotate: 0

# Stereo device number
stereo_dev_port: /dev/video20
# The width of the stereo camera image[640/1280]
stereo_single_cam_width: 640
# The width of the stereo camera image[400/800]
stereo_single_cam_height: 400

stereo_fps: 50
# Only support color sensors. Output: [0: raw image, 1: RGB image]
# The stereo color camera only supports a resolution of 1280*800.
stereo_color_mode: 0
# auto white balance for stereo rgb sensor only
stereo_awb: 1
# rgb digital gains for stereo rgb sensor only (works when awb-mode is off)
stereo_R_gain: 1.
stereo_G_gain: 0.6
stereo_B_gain: 1.3
#   -1: auto initial exposure （Initially set the exposure to automatic, then fix the value.）
#   1.0 ~ 507.0: manual exposure value
stereo_init_exposure: -1
# Stereo gain control [ 1.0 ~ 15.0 is manual : -1 auto gain ]
stereo_gain_value: -1
# Left camera rotation control [0: no rotation, 1: rotate 180 degrees]
left_cam_rotate_180: 0
# Right camera rotation control [0: no rotation, 1: rotate 180 degrees]
right_cam_rotate_180: 1

# Imu device number
imu_dev_port: /dev/video26
# The gravity acceleration value of the device location
gravity: 9.7946   
